/**
 * PiDesk 补充文件类型映射（手写维护，与生成物 mapping.ts 叠加）。
 * 上游 JetBrains 2023 集缺少 Office/媒体等常见类型；图标在 icons-extra/{light,dark}/。
 * `pnpm run gen:file-icons` 只重写 assets/ 与 mapping.ts，不碰本文件与 icons-extra/。
 */
export const EXTRA_FILE_EXTENSIONS: Readonly<Record<string, string>> = {
  pdf: "file_pdf",
  xls: "file_excel",
  xlsx: "file_excel",
  xlsm: "file_excel",
  xlsb: "file_excel",
  xlt: "file_excel",
  xltm: "file_excel",
  xltx: "file_excel",
  ods: "file_excel",
  numbers: "file_excel",
  doc: "file_word",
  docx: "file_word",
  docm: "file_word",
  dot: "file_word",
  dotx: "file_word",
  odt: "file_word",
  rtf: "file_word",
  pages: "file_word",
  ppt: "file_powerpoint",
  pptx: "file_powerpoint",
  pptm: "file_powerpoint",
  pps: "file_powerpoint",
  ppsx: "file_powerpoint",
  potx: "file_powerpoint",
  odp: "file_powerpoint",
  key: "file_powerpoint",
  bmp: "file_image",
  avif: "file_image",
  heic: "file_image",
  heif: "file_image",
  tif: "file_image",
  tiff: "file_image",
  txt: "file_text",
  log: "file_text",
  nfo: "file_text",
  mp3: "file_audio",
  wav: "file_audio",
  flac: "file_audio",
  m4a: "file_audio",
  aac: "file_audio",
  ogg: "file_audio",
  wma: "file_audio",
  mp4: "file_video",
  m4v: "file_video",
  mov: "file_video",
  webm: "file_video",
  mkv: "file_video",
  avi: "file_video",
  wmv: "file_video",
};
