import { fileURLToPath } from "node:url";
import { defineConfig } from "vitest/config";

const root = fileURLToPath(new URL(".", import.meta.url));

export default defineConfig({
  root,
  test: {
    include: ["src/**/*.test.ts"],
    coverage: {
      provider: "v8",
      // Only SDK source counts: tests are the measuring instrument, and types.ts
      // is generated by scripts/sync-view-sdk-types.mjs (docs/design/20 O1).
      include: ["src/**"],
      exclude: ["src/**/*.test.ts", "src/types.ts"],
      reporter: ["text", "json-summary"],
      reportsDirectory: "./coverage",
      all: true,
    },
  },
});
